spring.application.name=config-server
spring.cloud.config.server.native.search-locations=file:///C:/Users/10749650/Desktop/Documents/Springboot/micro-service/properties
spring.profiles.active=native
server.port=8888
